import theme from "./.theme/_theme.json";
const {
  colors,
  border_radius,
  font_family,
  font_weight,
  font_size,
  light_colors,
  screens,
  z_index,
} = theme;

const color = theme.schema === "dark" ? colors : light_colors;

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{jsx,tsx}"],
  theme: {
    colors: {
      //& Surface
      "surface-100": color.surface[100],
      "surface-200": color.surface[200],
      "surface-300": color.surface[300],
      "surface-400": color.surface[400],
      "surface-500": color.surface[500],
      "surface-600": color.surface[600],
      "surface-700": color.surface[700],
      "surface-800": color.surface[800],
      "surface-900": color.surface[900],
      // & Brand
      "brand-100": color.brand[100],
      "brand-200": color.brand[200],
      "brand-300": color.brand[300],
      "brand-400": color.brand[400],
      "brand-500": color.brand[500],
      "brand-600": color.brand[600],
      "brand-700": color.brand[700],
      "brand-800": color.brand[800],
      "brand-900": color.brand[900],
    },
    borderRadius: {
      none: border_radius.none,
      sm: border_radius.sm,
      DEFAULT: border_radius.DEFAULT,
      md: border_radius.md,
      lg: border_radius.lg,
      xl: border_radius.xl,
      "2xl": border_radius["2xl"],
      "3xl": border_radius["3xl"],
      full: border_radius.full,
    },
    fontFamily: {
      sans: font_family.sans,
      serif: font_family.serif,
      mono: font_family.mono,
    },
    fontWeight: {
      1: font_weight[1],
      2: font_weight[2],
      3: font_weight[3],
      4: font_weight[4],
      5: font_weight[5],
      6: font_weight[6],
      7: font_weight[7],
      8: font_weight[8],
      9: font_weight[9],
    },
    fontSize: {
      xs: font_size.xs.size,
      sm: font_size.sm.size,
      DEFAULT: font_size.DEFAULT.size,
      lg: font_size.lg.size,
      xl: font_size.xl.size,
      "2xl": font_size["2xl"].size,
      "3xl": font_size["3xl"].size,
      "4xl": font_size["4xl"].size,
      "5xl": font_size["5xl"].size,
      "6xl": font_size["6xl"].size,
      "7xl": font_size["7xl"].size,
      "8xl": font_size["8xl"].size,
      "9xl": font_size["9xl"].size,
    },
    screens: {
      "5sm": screens["5sm"],
      "4sm": screens["4sm"],
      "3sm": screens["3sm"],
      "2sm": screens["2sm"],
      sm: screens["sm"],
      md: screens["md"],
      lg: screens["lg"],
      xl: screens["xl"],
      "2xl": screens["2xl"],
      "3xl": screens["3xl"],
      "4xl": screens["4xl"],
      uxl: screens["uxl"],
      "2uxl": screens["2uxl"],
      "3uxl": screens["3uxl"],
    },
    zIndex: {
      auto: z_index.auto,
      "negative-2": z_index["negative-2"],
      "negative-1": z_index["negative-1"],
      "negative-0": z_index["negative-0"],
      "DEFAULT:": z_index.DEFAULT,
      "positive-0": z_index["positive-0"],
      "positive-1": z_index["positive-1"],
      "positive-2": z_index["positive-2"],
    },
  },
  plugins: [],
};
